"""
Domain Events - Events for cross-cutting concerns and external notifications.

These events follow the pattern established in AgentGit's EventBus.
"""

from .checkpoint_events import (
    BranchCreatedEvent,
    CheckpointCreatedEvent,
    RollbackPerformedEvent,
)
from .environment_events import (
    DependenciesAddedEvent,
    DependenciesRemovedEvent,
    DependenciesUpdatedEvent,
    DependencyOperationFailedEvent,
    EnvironmentCleanupCompletedEvent,
    EnvironmentCleanupStartedEvent,
    EnvironmentCreatedEvent,
    EnvironmentCreationFailedEvent,
    EnvironmentCreationStartedEvent,
    EnvironmentDeletedEvent,
    EnvironmentEvent,
    EnvironmentLockAcquiredEvent,
    EnvironmentLockReleasedEvent,
    EnvironmentLockTimeoutEvent,
    EnvironmentSyncedEvent,
    EnvironmentSyncFailedEvent,
)
from .execution_events import (
    ExecutionCancelledEvent,
    ExecutionCompletedEvent,
    ExecutionFailedEvent,
    ExecutionPausedEvent,
    ExecutionResumedEvent,
    ExecutionStartedEvent,
    WTBEvent,
)
from .file_processing_events import (
    BlobCreatedEvent,
    BlobDeletedEvent,
    CheckpointFileLinkCreatedEvent,
    CheckpointFileLinkVerifiedEvent,
    FileCommitCreatedEvent,
    FileCommitDeletedEvent,
    FileCommitVerifiedEvent,
    FileRestoredEvent,
    FileRestoreFailedEvent,
    FileTrackingCompletedEvent,
    FileTrackingFailedEvent,
    FileTrackingStartedEvent,
)
from .langgraph_events import (
    LANGGRAPH_EVENT_TYPE_MAP,
    LangGraphAuditEvent,
    LangGraphAuditEventType,
    create_audit_event_from_langgraph,
    create_checkpoint_audit_event,
    create_superstep_audit_event,
    map_langgraph_event_type,
)
from .node_events import (
    NodeCompletedEvent,
    NodeFailedEvent,
    NodeSkippedEvent,
    NodeStartedEvent,
)
from .ray_events import (
    RayActorFailedEvent,
    RayActorInitializedEvent,
    RayActorPoolCreatedEvent,
    RayActorRestartedEvent,
    RayBackpressureAppliedEvent,
    RayBackpressureReleasedEvent,
    RayBatchTestCancelledEvent,
    RayBatchTestCompletedEvent,
    RayBatchTestFailedEvent,
    RayBatchTestProgressEvent,
    RayBatchTestStartedEvent,
    RayEvent,
    RayEventType,
    RayVariantExecutionCancelledEvent,
    RayVariantExecutionCompletedEvent,
    RayVariantExecutionFailedEvent,
    RayVariantExecutionStartedEvent,
    RayVariantFilesTrackedEvent,
    RayVariantFilesTrackingFailedEvent,
)
from .workspace_events import (
    # Actor Lifecycle Events
    ActorCreatedEvent,
    ActorKilledEvent,
    ActorResetEvent,
    FileRestoreEvent,
    FileRestoreFailedEvent,
    # File Operations Events
    FileSnapshotCreatedEvent,
    ForkCompletedEvent,
    # Fork Events
    ForkRequestedEvent,
    OrphanCleanupCompletedEvent,
    # Orphan Events
    OrphanWorkspaceDetectedEvent,
    ResourcesReacquiredEvent,
    # Resource Events
    ResourcesReleasedEvent,
    # Venv Events
    VenvCreatedEvent,
    VenvInvalidatedEvent,
    VenvMismatchWarningEvent,
    VenvRestoredEvent,
    VenvReusedEvent,
    WorkspaceActivatedEvent,
    WorkspaceCleanedUpEvent,
    # Workspace Lifecycle Events
    WorkspaceCreatedEvent,
    WorkspaceDeactivatedEvent,
)

__all__ = [
    # Base
    "WTBEvent",
    # Execution events
    "ExecutionStartedEvent",
    "ExecutionPausedEvent",
    "ExecutionResumedEvent",
    "ExecutionCompletedEvent",
    "ExecutionFailedEvent",
    "ExecutionCancelledEvent",
    # Node events
    "NodeStartedEvent",
    "NodeCompletedEvent",
    "NodeFailedEvent",
    "NodeSkippedEvent",
    # Checkpoint events
    "CheckpointCreatedEvent",
    "RollbackPerformedEvent",
    "BranchCreatedEvent",
    # LangGraph events
    "LangGraphAuditEvent",
    "LangGraphAuditEventType",
    "LANGGRAPH_EVENT_TYPE_MAP",
    "map_langgraph_event_type",
    "create_audit_event_from_langgraph",
    "create_checkpoint_audit_event",
    "create_superstep_audit_event",
    # Environment events
    "EnvironmentEvent",
    "EnvironmentCreationStartedEvent",
    "EnvironmentCreatedEvent",
    "EnvironmentCreationFailedEvent",
    "EnvironmentDeletedEvent",
    "DependenciesAddedEvent",
    "DependenciesUpdatedEvent",
    "DependenciesRemovedEvent",
    "DependencyOperationFailedEvent",
    "EnvironmentSyncedEvent",
    "EnvironmentSyncFailedEvent",
    "EnvironmentCleanupStartedEvent",
    "EnvironmentCleanupCompletedEvent",
    "EnvironmentLockAcquiredEvent",
    "EnvironmentLockReleasedEvent",
    "EnvironmentLockTimeoutEvent",
    # File Processing events (2026-01-15)
    "FileCommitCreatedEvent",
    "FileCommitDeletedEvent",
    "FileCommitVerifiedEvent",
    "FileRestoredEvent",
    "FileRestoreFailedEvent",
    "CheckpointFileLinkCreatedEvent",
    "CheckpointFileLinkVerifiedEvent",
    "BlobCreatedEvent",
    "BlobDeletedEvent",
    "FileTrackingStartedEvent",
    "FileTrackingCompletedEvent",
    "FileTrackingFailedEvent",
    # Ray events (2026-01-15)
    "RayEventType",
    "RayEvent",
    "RayBatchTestStartedEvent",
    "RayBatchTestCompletedEvent",
    "RayBatchTestFailedEvent",
    "RayBatchTestCancelledEvent",
    "RayBatchTestProgressEvent",
    "RayActorPoolCreatedEvent",
    "RayActorInitializedEvent",
    "RayActorFailedEvent",
    "RayActorRestartedEvent",
    "RayVariantExecutionStartedEvent",
    "RayVariantExecutionCompletedEvent",
    "RayVariantExecutionFailedEvent",
    "RayVariantExecutionCancelledEvent",
    "RayVariantFilesTrackedEvent",
    "RayVariantFilesTrackingFailedEvent",
    "RayBackpressureAppliedEvent",
    "RayBackpressureReleasedEvent",
    # Workspace events (2026-01-16)
    "WorkspaceCreatedEvent",
    "WorkspaceActivatedEvent",
    "WorkspaceDeactivatedEvent",
    "WorkspaceCleanedUpEvent",
    "FileSnapshotCreatedEvent",
    "FileRestoreEvent",
    "FileRestoreFailedEvent",
    "ForkRequestedEvent",
    "ForkCompletedEvent",
    "VenvCreatedEvent",
    "VenvReusedEvent",
    "VenvInvalidatedEvent",
    "VenvMismatchWarningEvent",
    "VenvRestoredEvent",
    "ActorCreatedEvent",
    "ActorResetEvent",
    "ActorKilledEvent",
    "ResourcesReleasedEvent",
    "ResourcesReacquiredEvent",
    "OrphanWorkspaceDetectedEvent",
    "OrphanCleanupCompletedEvent",
]

